### ISSUE TITLE
how to re-sign an APK with a stripped v2 signature so it can be installed?

### ISSUE THREAD

**Issue by winstonma** [obfusk/apksigtool#71]
Actually this is the combined result of using [apksigcopier](https://github.com/obfusk/apksigcopier) and apksigtool. First of all I got an apk that the signature is stripped and would like to install this apk on my device.

When I try to install the apk using adb install it gives me the following error:
```bash
$ adb install -r floatingbutton-release.apk 
Performing Streamed Install
adb: failed to install floatingbutton-release.apk: Failure [INSTALL_PARSE_FAILED_NO_CERTIFICATES: Failed to collect certificates from /data/app/vmdl2052061837.tmp/base.apk: META-INF/RELEASE-.SF indicates /data/app/vmdl2052061837.tmp/base.apk is signed using APK Signature Scheme v2, but no such signature was found. Signature stripped?]
```

Actually I have the older installable version of this apk so I would like to transfer the signature from the old apk to the new apk.

```bash
$ apksigcopier extract floatingbutton-release-old.apk meta
Error: Unsupported create_version.

$ apksigcopier patch meta floatingbutton-release.apk out.apk
Error: Unexpected metadata.

$ adb install -r out.apk 
Performing Streamed Install
adb: failed to install out.apk: Failure [INSTALL_PARSE_FAILED_NO_CERTIFICATES: Failed to collect certificates from /data/app/vmdl548595790.tmp/base.apk: Attempt to get length of null array]
```

Then I tried to clean using apksigtool:
```bash
$ apksigtool clean floatingbutton-release.apk 
Error: No APK Signing Block.
```

Then I tried to remove the META-INF folder from the new apk
```bash
# Delete META-INF folder
$ zip -d floatingbutton-release.apk "META-INF/*"

$ apksigcopier patch meta floatingbutton-release.apk out.apk

$ adb install -r out.apk 
Performing Streamed Install
adb: failed to install out.apk: Failure [INSTALL_PARSE_FAILED_NO_CERTIFICATES: Failed to collect certificates from /data/app/vmdl79553399.tmp/base.apk using APK Signature Scheme v2: SHA-256 digest of contents did not verify]
```

I am a newbie and I am not sure how to properly sign the stripped apk. May I know how should I get the apk installed on my device? Thanks

**Comment by obfusk** [comment]
NB: `apksigcopier` is a tool that allows using an [android APK signature](https://source.android.com/docs/security/features/apksigning) as a build input (by copying it from a signed APK to an unsigned one), making it possible to create a ([bit-by-bit identical](https://reproducible-builds.org/docs/definition/)) [reproducible build](https://f-droid.org/docs/Reproducible_Builds/) from the source code without having access to the private key used to create the signature.

> Actually I have the older installable version of this apk so I would like to transfer the signature from the old apk to the new apk.

That's simply not possible unless the APKs are 100% identical apart from the signature, but then there would be no point in copying the signature in this scenario as you could simply install the signed APK; but an older and thus non-identical version will never work.

The signature verifies the integrity of the APK. For v2/v3 signatures that means even a single bit being different makes the signature invalid. For the old v1 signatures ZIP metadata may differ, but the files in the APK must still be 100% identical.

There is no point in trying to copy the signature to an unsigned APK unless that APK is *completely identical to the signed APK apart from the missing signature* as the signature cannot possibly be valid for any other APK.

Under some circumstances, copying the signature does *seem to* work (since the copying doesn't check whether the signature is valid for the APK it copies it to), but it won't be valid so there's no point in doing so.

**Comment by winstonma** [comment]
@obfusk Thanks for the help

Is it possible to convert a signature stripped APK into a unsigned APK?

**Comment by obfusk** [comment]
> Is it possible to convert a signature stripped APK into a unsigned APK?

Maybe. Depending on *how* the signature was stripped it may not be possible to convert it to an APK that's *identical* to the original unsigned APK (as that requires identical ZIP metadata, not just identical files in the APK), which would be required for signature copying, but simply removing the v1 signature files should work.

But, again, how would that help you? You still can't copy the signature from a different APK, even if it's the same app.

**Comment by obfusk** [comment]
If you want to install the APK, but the signature does not need to be identical, you can simply create your own key and sign the stripped/unsigned APK with [`apksigner`](https://developer.android.com/studio/command-line/apksigner). That would make it impossible to upgrade from an existing install with a different signature, but if that's not an issue it should work.

**Comment by winstonma** [comment]
> But, again, how would that help you? You still can't copy the signature from a different APK, even if it's the same app.

I am thinking I uninstall the app from the device and then install the unsigned version of the app.


> If you want to install the APK, but the signature does not need to be identical, you can simply create your own key and sign the stripped/unsigned APK with [`apksigner`](https://developer.android.com/studio/command-line/apksigner). That would make it impossible to upgrade from an existing install with a different signature, but if that's not an issue it should work.

Thanks let me try to sign the stripped apk and see if that work

**Comment by obfusk** [comment]
I do hope you can get it to work, but none of this has anything to do with `apksigtool` or `apksigcopier` so this issue tracker is not the right place to discuss your problem.

**Comment by winstonma** [comment]
Sure originally I would like to use `clean` function to turn the signature-stripped APK into unsigned APK. Not sure if it is possible to add this capability to the `apksigtool`.

This is the running result of apksigtool running against the signature-stripped APK
```bash
$ apksigtool clean floatingbutton-release.apk 
Error: No APK Signing Block.

$ apksigner verify floatingbutton-release.apk
DOES NOT VERIFY
ERROR: JAR signer RELEASE-.RSA: JAR signature META-INF/RELEASE-.SF indicates the APK is signed using APK Signature Scheme v2 but no such signature was found. Signature stripped?
```

Eventually the signature-stripped APK can be signed using the following command:
```bash
# Create Signature (1 time only)
keytool -genkey -v -keystore my-release-key.keystore -alias alias_name -keyalg RSA -keysize 2048 -validity 10000

# Delete META-INF folder
$ zip -d floatingbutton-release.apk "META-INF/*"

# Sign the APK
$ apksigner sign --ks my-release-key.keystore floatingbutton-release.apk
```

I was thinking if it is possible to remove the `META-INF` folder for the signature-stripped APK using apksigtool

**Comment by obfusk** [comment]
> Sure originally I would like to use clean function to turn the signature-stripped APK into unsigned APK.

That's not what the `clean` command is for. That's meant to clean the signing block: i.e. keep the signature but remove things like the "dependency info block" containing encrypted data only google can read. It does not remove the signature.

**Comment by winstonma** [comment]
Thanks for the description. I think I misunderstand the clean command. I think I would use the [zip method](https://gist.github.com/marcelosantos/f676c31bc48411613cbd3bb8253710e4) to remove the signature instead.

**Comment by obfusk** [comment]
That should work. You can use `apksigcopier` for that if you really want, but you have to use the Python API:

```py
import apksigcopier
apksigcopier.copy_apk("signed.apk", "unsigned.apk", exclude=apksigcopier.exclude_meta)
```
